apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: {{ .Values.redpanda.image }}
          args:
            - redpanda
            - start
            - --overprovisioned
            - --smp
            - "1"
            - --memory
            - 1G
            - --reserve-memory
            - 0M
            - --node-id
            - "0"
            - --check=false
            - --kafka-addr
            - PLAINTEXT://0.0.0.0:9092
            - --advertise-kafka-addr
            - PLAINTEXT://redpanda:9092
            - --pandaproxy-addr
            - 0.0.0.0:8082
            - --advertise-pandaproxy-addr
            - redpanda:8082
          ports:
            - containerPort: 9092
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda
spec:
  selector:
    app: redpanda
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: pandaproxy
      port: 8082
      targetPort: 8082
