global:
  scrape_interval: 5s

scrape_configs:
  - job_name: kyc-api
    static_configs:
      - targets: ["api:8080"]
  - job_name: redpanda
    metrics_path: /public_metrics
    static_configs:
      - targets: ["redpanda:9644"]
